version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: optimal_mysql_db
    restart: unless-stopped
    env_file: ./optimalbackend/.env
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    volumes:
      -db:/var/lib/mysql

  back-end:
    image: optimalhandyman-backend:1.0
    container_name: optimal_node_server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
    depends_on:
      - mysqldb

  front-end:
    image: teddtycoon/optimalhandyman-website:latest
    container_name: optimal_react_frontend
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://back-end:5000
    depends_on:
      - back-end
volumes:
  db:
