# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - optimalhandyman

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies and build frontend
        run: |
          npm install
          npm run build --if-present
        working-directory: ./optimal

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip optimal
        working-directory: .

      - name: Copy build to backend
        run: |
          cp -r optimal/build optimalbackend/

      - name: Install backend dependencies
        run: |
          npm install
        working-directory: ./optimalbackend

      - name: Zip backend artifact for deployment
        run: |
          zip -r backend_release.zip optimalbackend
        working-directory: .
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: |
            release.zip
            backend_release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app
          path: .

      - name: Unzip frontend artifact
        run: unzip release.zip -d .

      - name: Unzip backend artifact
        run: unzip backend_release.zip -d .
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C3F7BEEEBDE84FEE838AA9751B5D4C04 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_32FB65A3AB224D2EA999687B2A863A3A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EBBAB566D3494799A52E5E57E0F9002A }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'optimalhandyman'
          slot-name: 'Production'
          package: .
          
